### ISSUE TITLE
On Windows 11 with VSCode, the yeferyv.retronvim directory was different and thus it couldn't find nvim.exe after the latest update.

### ISSUE THREAD

**Issue by JZsmitty** [YeferYV/RetroNvim#2]
The directory that got set by default after updating to the latest version of Retrovim was
X:\Users\[theusername]\.vscode\extensions\yeferyv.retronvim-0.1.0\bin\nvim.exe

However, it is actually
X:\Users\[theusername]\.vscode\extensions\yeferyv.retronvim-0.1.0-win32-x64\bin\nvim.exe

So, I had to go into the Neovim settings and change it there. I am guessing this has something to do with a quirk of Windows, or perhaps since I have been using RetroNvim for a while, this might have been a previous name for the directory that doesn't get changed on updating the plugin.

So far everything else is working for me after the update. I will let you know if I run into anything else.

**Comment by YeferYV** [comment]
Thanks for the bug report, this was fixed by ` it turns out that uploading platform specific `.vsix` package adds the `win32` suffix, for now you can install the prerelease or github release, I will drop a new release in a few days

**Comment by YeferYV** [comment]
I'm replaying on my phone and I close it by mistake

**Comment by YeferYV** [comment]
Since there is a new release I'm closing this issue
